[package]
name = "blinky"
version = "0.1.0"
authors = ["Erwin Gribnau <erwin@gribnau.org>"]

[dependencies]

[profile.dev]
panic = "abort"
opt-level = "s"
lto = false
codegen-units = 1
incremental = false

[dependencies.stm32f103xx]
version = "0.8.0"
features = ["rt"]

[dependencies.cortex-m]
version = "0.4.3"

[dependencies.cortex-m-semihosting]
version = "0.2.0"

[dependencies.cortex-m-rt]
version = "0.3.13"
features = ["abort-on-panic"]